compile:
	npx hardhat compile

deploy_Celestial:
	npx hardhat run ignition/modules/celestial.ts --network baseSepolia

deploy_Gladiator:
	npx hardhat run ignition/modules/gladiator.ts --network baseSepolia

verify_Celestial:
	npx hardhat verify --network baseSepolia 0xa3DdAd7D56f4F77F260FF6A49510Bd3E137b5808

verify_Gladiator:
	npx hardhat verify --network baseSepolia 0x1A00F7E32Ba27EF52ca8B71c55eE090b1645e592
